blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/wezzcoetzee/.github/discussions
    about: Use Discussions for general questions instead of opening an issue.
